### ISSUE TITLE
An error occurred while trying to retrieve the default Docker context : exit status 1

### ISSUE THREAD

**Issue by tempest2023** [will-moss/isaiah#14]
Hi, It's an awesome project and I can't wait to try it.
However, there were several problems when I tried to install Isaiah.
1. It needs `sudo` permission to run `mv isaiah $DESTINATION/` and `chmod 755 $DESTINATION/isaiah` in `local-install.sh`. Maybe it's better to show a description to remind the user to add it.
2. After I manually added it, and created the `.env`, and run `isaiah`, I got an error: `An error occurred while trying to retrieve the default Docker context : exit status 1`. This message is from `client.go` at line 65. I was surprised that my docker doesn't support `docker context show` command. My docker version is 20.10.17 and the `docker context show` was introduced in Docker version 19.03.

Here is my docker version:
```
> docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
By the way, my docker supports `docker context ls` to inspect, and here is the result
```
> docker context ls
NAME        DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
```

Are there any ways to solve this problem without updating my docker version? I got many docker images and containers, so updating docker is a hard problem for me :<
I'll try to change the code , using other ways to get the docker context and compile it locally. I think it should work for me.

**Comment by will-moss** [comment]
Hi !

Thanks a lot for the kind words, and for providing all those details.

First and foremost, you are defnitely right for the sudo requirement on the install script. I overlooked it, and failed to even mention it in the README. I will try to improve everything by mentioning this requirement in the README, add a notice in the install script to warn the user when they're not sudo, and potentially, add the ability to choose a custom directory rather than the default `/usr/bin`. Thanks a lot for pointing that out.

Second, please note that, in a previous issue, a user with 200+ resources was able to update Docker without problem. It wasn't as big of a jump as 20.10 -> 26.0, but still, it worked. As a result, I wouldn't be surprised if, for you as well, updating Docker could fix the situation. Read further though.

I think you could quickly get around the error on `docker context show` crashing (for a reason I cannot explain. The code just invokes a system command so, it has to do with how the system is set up. Maybe `docker` isn't available in the $PATH? Or maybe does running `docker` require extra permissions that the `isaiah` executable doesn't have?) by defining the environment variable `DOCKER_HOST` to `/var/run/docker.sock`. This will instruct `isaiah` where the socket is. As a consequence, it won't even try to run `docker context show`.

Let me know if that works, and be assured that I'll try to help even if you don't have the minimal supported version of Docker. 

PS : Just a thing. I'm afraid that, even if you succeed in launching Isaiah, some features (like the Overview, which is disable-able fortunately) won't work properly. You know the risks already!

**Comment by tempest2023** [comment]
Thanks for your suggestions.
After setting `DOCKER_HOST` as `unix:///var/run/docker.sock`, isaiah works!

Here are the steps I did.

1. I checked the env variables, my `docker` is under `/usr/bin/docker`.
2. I tried `docker context show` directly, and here is the output
```
docker context show

Usage:  docker context COMMAND

Manage contexts

Commands:
  create      Create a context
  export      Export a context to a tar or kubeconfig file
  import      Import a context from a tar or zip file
  inspect     Display detailed information on one or more contexts
  ls          List contexts
  rm          Remove one or more contexts
  update      Update a context
  use         Set the current docker context

Run 'docker context COMMAND --help' for more information on a command.
```
3. isaiah executable belongs to the current user who has permission to run docker.

I set the DOCKER_HOST correctly and isaiah is able to find my docker context and work.

**Comment by will-moss** [comment]
Alright! Thanks a lot for your feedback.

I'm glad everything works now.

May I close the issue?

**Comment by tempest2023** [comment]
Sure
