### ISSUE TITLE
[UX] Indicate there are more icons at bottom on mobile

### ISSUE THREAD

**Issue by shizunge** [will-moss/isaiah#17]
When accessing *isaiah* on mobile devices, there are a few icons at the bottom of the screen.

I did not realize there are more than 4 icons there at beginning, and learnt there are more icons by accident.

I think it would be a better to have an indicator or something in the docker at the bottom of the screen to tell user (especially the first time user) there are more icons. It would help first time user.

![image](https://github.com/will-moss/isaiah/blob/master/assets/CAPTURE-14.png?raw=true)

**Comment by shizunge** [comment]
I found this at very bottom of README

https://github.com/will-moss/isaiah?tab=readme-ov-file#a-feature-that-works-on-desktop-is-missing-from-the-mobile-user-interface

**Comment by will-moss** [comment]
Hi,

Thanks a lot for opening that issue (along with all the others!) and for providing those details.

I have just published a new release that should address the issue mentioned here.

From now on, when using a mobile device, a popup message will be shown on first launch, indicating that more buttons are available in the menu, and it's scrollable too.

I hope it works better for everyone now, as that issue was also mentioned earlier by another user.

**Comment by shizunge** [comment]
Thank you for the update. And thank you for making it work on both desktop and mobile devices. Sorry that I have not tried the new version.

I was thinking that a" ..." Or humberger menu may be better than sliding left and right solution on mobile. I don't do front end code so I am not sure how difficult it is. Just some random thoughts.

Here is how it looks like on the GitHub mobile web interface:
![Screenshot_20241004-085518](https://github.com/user-attachments/assets/d758432d-9db5-439e-87fe-3e2796573dba)

**Comment by will-moss** [comment]
Hi again!

Thanks to you, and no need to be sorry.

I've just released a new version, that now uses a hamburger menu on mobile.

I'd definitely agree that it "feels" better now, but I let you judge for yourself!

**Comment by shizunge** [comment]
Looks good. Thanks
