### ISSUE TITLE
[document] Configuration for multi-node clients

### ISSUE THREAD

**Issue by shizunge** [will-moss/isaiah#19]
Thank you for listing all [configurations](https://github.com/will-moss/isaiah?tab=readme-ov-file#configuration).

Could you pleae indicate which are only used for the clients in multi-node, which are only used in the master and which apply to both client and master.

Best,

**Comment by will-moss** [comment]
You're welcome, and thanks for opening the issue.

I've just published an updated README, with a detail on which setting belongs to which role.

Is it what you had in mind?

**Comment by shizunge** [comment]
Do the configurations that are not mentioned in the commit above apply only to the master node?
Only the configurations with "for Agent nodes" or "for both Master and Agent nodes" apply to agent nodes?

**Comment by will-moss** [comment]
I would rather say : 

- The settings that have no comment about multi-node deployments are all both available for Master and Agent nodes, except for `SSL_ENABLED` and `SERVER_PORT` since Agent nodes do not behave like a server that listens for incoming connections. So, for instance, you could have different `TABS_ENABLED` for each node, regardless of them being a Master or Agent. Finally, these settings are designed to work in a single-node deployment primarily, without multi-node enabled at all.

- The settings that have a comment about multi-node deployments will be interpreted only in a multi-node deployment, and fully ignored in a single-node deployment. I would even say that they are absolutely required for a multi-node deployment to work. And the ones that mention "for Agent node" will be ignored by the Master node.

**Comment by shizunge** [comment]
That clarifies the question I had, especially "*you could have different TABS_ENABLED for each node, regardless of them being a Master or Agent.*"

I think you can close the bug, though I wish you could put what you said above into the documents.
* Agent node does not use SSL_ENABLED and SERVER_PORT
* We could have different TABS_ENABLED for each node, regardless of them being a Master or Agent.
* Maybe put multi-node only config like SERVER_ROLE MASTER_HOST MASTER_SECRET etc. into a separated table.

Thank you!

**Comment by will-moss** [comment]
Thanks for your feedback and confirmation!

I have just added a section in the README, following your recommendation.

Hoping that it helps other users, and meets your expectations!
