### ISSUE TITLE
"Open System Shell" Errors

### ISSUE THREAD

**Issue by Vinylwalk3r** [will-moss/isaiah#5]
First of, thank you for making this project! Its really great.
---
Evironment/s:
1. Docker container on Unraid
2. Remote Docker socket using port 2375
---
Problem:
When I press Shift+S to open up System Shell, I get this error:
`Error     fork/exec    /bin/sh: no such file or directory`
This happens in BOTH environments. 
I've checked the logs for the Docker container on environment 1, but they show nothing at all.
If you want or need any more info or logs, just ask.

**Comment by will-moss** [comment]
Hi,

Thanks a lot for the kind words, and for opening the issue with these information.

In my understanding, the error is the following : "/bin/sh" does not exist inside your system.

As a result, when isaiah tries to spawn a shell (a.k.a. run "/bin/sh" inside your os), it crashes, because it doesn't exist.

The solution should be the following : 
- Locate the bash executable on your system. (Is it "/bin/bash" ? or maybe "/usr/bin/bash" ? or something else?).
- You can try to run (inside an SSH session / in a terminal on your system) the command "which bash" or "which sh" to retrieve the bash's executable path.
- When you've found the bash's executable path on your system, redeploy Isaiah, but this time, you must define the setting "TTY_SERVER_COMMAND" beforehand, and set it to the path of the executable you've found before.
- So, you should have something like : `TTY_SERVER_COMMAND :  "/path/to/your/bash -i"`.

Trying to put it differently, and shorter : 
- Locate the path to the `bash / sh` program on your server.
- Set the variable `TTY_SERVER_COMMAND = "/the/path/you/found/just/before"` in your Docker environment variables
- Recreate your container with this variable.

Does that help? Please feel free to let me know if I can explain better.

**Comment by Vinylwalk3r** [comment]
Thanks for your quick and well explained answer! Your help was very easy to follow, good work!

Now, I've done some digging myself, and I can confirm a few things:
- If I try to open Docker containers shell, it immediately crashes. It seems like it's something strange going on inside the container itself.
- The same problem persists on my remote machine, even though that one is a direct connection to the docker socket. No Isaiah container is present on that machine.

I tried your solution, running "which sh / bash" and setting a env variable in the docker container to the path I got (I also tried with the -i parameter but nothing there either). Still, the error persists. No change. I tried for both shell and bash. The only change was the error said it couldn't find bash either. 

I'm starting to wonder if this may be deeper problem in the Docker file? I'm not well versed in how to write them, but could it be that something needs to be loaded in the Docker file to be able to interact with a terminal?

The thing is also, all of my other containers can flawlessly interact with their shells, Isaiah is the only one with a issue.

**Comment by will-moss** [comment]
Alright, thanks a lot for that feedback with those details.

I think I am onto something now.

Before I even start, I have just realized that Isaiah is available under Unraid Community Apps. Please note that, having never ever used Unraid, I'm not too sure how that all works, especially when it comes to Community Apps. I didn't even know that someone had "published" Isaiah there (thanks a lot to whoever took the time to do that! Much appreciated).

Now, for starters, let's make sure that we are on the same page for a few things : 
- In general, Isaiah can be deployed in two different fashions : as a standalone app, or as a Docker container.
- As a result, if you install Isaiah as a standalone app (read, as a binary that runs directly on your server, with no virtualization, no container, no Docker), Isaiah will, indeed, have access to your system. So, running `/bin/sh` or `/bin/bash` should work flawlessly if those are installed on your server. So, as a standalone app, Isaiah should be able to open a shell on your server without any issue.
- Now, if you installed Isaiah using Docker, Isaiah does not run on your server directly. Rather than that, Isaiah runs inside a Docker container. As a result, Isaiah doesn't have access to your whole system, it only has access to what's inside the Docker container it belongs to. So, running `/bin/sh` or `/bin/bash` will only work if the Docker container that contains Isaiah has those binaries installed.

Now that we know how everything works, let's try to see how to solve your issue in every scenario.

Scenario 1 : Standalone deployment, no Docker Container whatsoever
- Open a terminal inside your server (using SSH, or booting into your server physically if applicable).
- Run the command `which sh` or `which bash` (`bash` is usually preferred over `sh` because it has more features)
- You should now have an absolute path to your `bash` program.
- Take that absolute path, and set the configuration variable `TTY_SERVER_COMMAND = <the-path-you-just-got>` inside your environment or `.env` file.
- Stop Isaiah, and restart it. 
- Try to open a system shell by typing `S`, and it should work.
- If it doesn't work, look what the error says, and ensure that, if the error is `XXX not found`, XXX is equal to the path you've set just before. If not, try to stop and restart isaiah again to make sure that your configuration setting was, indeed, refreshed.

Scenario 2 : Docker deployment, Isaiah is inside a Docker container
- Before doing anything, please note that Isaiah can't do anything outside of the container. I mean, you can open a "System shell", but in that case, "System" refers to the Docker container itself, not the system where Docker is installed.
- In that scenario, I believe it won't be possible at all to open a "System shell" inside the Docker container that contains Isaiah. The reason is, to make the container super lightweight, the Docker container is based on the Docker image named `scratch` which is....absolutely empty. As a result, the Docker container where Isaiah runs doesn't have a shell at all. So, opening a "System shell" won't be doable here.

Ultimately, we can talk about `Container shell` rather than `System shell`, a.k.a. the shell you open inside the Docker containers that Isaiah manages. (Example : You have installed Isaiah on Unraid, and Isaiah enables you to see your 42 containers, 20 images, 10 volumes, 5 networks, etc. Here, Isaiah should be able to open a shell inside any of your 42 containers, provided that those containers have a bash installed). Here, if the native command that Isaiah uses doesn't work for you, you can tweak it using the variable `TTY_CONTAINER_COMMAND` in your configuration settings. By default, it uses `/bin/sh -c xxxxx`, but that may not work for you. Also, please note that it is critical that the containers you try to attach to have `sh / bash` installed.

Does that help? You also said that, trying to open container shells, it kept crashing. Is there any chance you could share the error that pops up (if any)?

Cheers!

**Comment by Vinylwalk3r** [comment]
Anytime!
Okay, I understand what your saying. So in a Docker container, System Shell will never work. And opening the containers own shell is kinda useless in this context. After reading what you've explained, it's logical that it shouldn't work.

Also, I bloody give up trying to run it as a standalone app. The installing and running part is easy (thanks to that GREAT one-liner script that's does the install that you wrote!) but my lord is passing a .env file to the starting script ever a PITA! I just can't figure out how to do it without writing several scripts or using way to long commands for what I'm trying to do. Not having access to System Shell through Isaiah would be kinda awesome, but I already have a semi-working Kasm SSH set up for that...so I can live without it.

Maybe you could add a little footnote in the features that says "System Shell is not available when running inside a Docker Container"? Since we now know that inside Docker, Sys Shells cant be run.

Yeah, when I tried to open the Containers own shell, it immediately crashes without any error message of log output at all. Nothing, just the tab closing itself and gone.
I can also confirm that Isaiah can open Container Shells on other containers from inside a its own Docker Container. So that works flawlessly.

I still find it interesting that Isaiah is not capable of opening a System Shell on my remote machine, since it isn't confined to a Docker container there. Just a Docker Socket connection. Or maybe that's the problem? Trying to exec a System Shell THROUGH the Docker Socket is not possible / allowed?

Also, quick question. Are you planning on adding a way to use Docker Compose from inside Isaiah? Or editing the environment variables? (this could probably be done using the docker commands from a System shell...if you can access it)
I tried the "Pull Image -> Run Image" features (which work great!) but was wondering if you planning on expanding their capabilities? Some way to set variables, volumes and other settings before running an image would be SUPER! A finishing touch. Do that and, imo, Isaiah is a one-stop shop for Docker management.

**Comment by will-moss** [comment]
Alright, thanks again for explaining everything, and I'm glad it all makes sense.

One by one : 

- You said you had issues running Isaiah as a standalone app because passing a `.env` file to the starting script was troublesome. Are you sure that you've tried to do it """properly"""? I mean, Isaiah will look for the `.env` file that is directly available in the current working directory. So, assuming that you have access to your server via SSH and Isaiah was installed via the install script, and if I'm not mistaken, this is what should be done : 
  - SSH into your server :  `ssh your-user@your-server.tld`
  - Create a new `.env` file wherever you want : `touch .env`
  - Fill in that `.env` file with your configuration :  `nano .env` or `vim .env` and edit the file, or send it via `scp`
  - Run Isaiah from the same directory where your `.env` file is located : `isaiah`
 - You should now be done, and your `.env` file will be used automatically.
 - To make sure that your `.env` file is well loaded, you can set up intentionally-wrong settings to cause Isaiah to crash on startup (e.g. set a negative `SERVER_PORT`). This way, you'll be sure that your settings are indeed loaded from the `.env` file.
- Loading a custom `.env` file should be an easy step, or else there's something I've missed and I should fix it asap for you and other users.

- Regarding the footnote, thank you very much! I have just published a new release for that. From now on, trying to open a system shell when Isaiah is inside a Docker Container will display an error, explaining that it's not possible due to being confined to the Docker Container. I also added a few words in the README for that.

- Regarding your point : Not being able to open a system shell on your remote machine : Am I understanding correctly that you currently have two machines? If so, you have Isaiah installed on machine A, and it manages Docker resources on machine B, right? And you would like to open a system shell on machine B from machine A, is that correct? If so, it is not possible at the moment, nor do I think it will ever be possible. Isaiah can only open a system shell on the system where it is installed, because it has access to the locally-installed executables. However, it can't log into other machines and run executables there. You've also said "trying to open a system shell THROUGH the Docker Socket is not possible / allowed?" and that's exactly the current "limitation". The Docker socket (that exposes to the Docker Engine API) can only run executables inside Docker Containers, nowhere else. So, from A to B, you can run executables (e.g. container shell) inside Docker Containers on B, but you can't run executables on B directly. ([Relevant documentation](https://docs.docker.com/engine/api/v1.37/#tag/Exec/operation/ContainerExec))

- Regarding the container shells crashing, along with the `.env` file, I think there could be a way to troubleshoot and solve these issues "more easily" provided that you have the time for it. Let me explain. Rather than using Isaiah from Unraid, you could install Isaiah on your local machine (your current computer), and have it communicate with your remote Docker socket using port 2375. That way, you'll be able to test a few things : Is your `.env` well loaded locally? Does the `isaiah` executable crash when trying to open container shells remotely? All in all, is there anything different between Unraid and your machine that could explain the issues you were facing?

Ultimately, regarding the project and its evolution (thanks a lot for the kind words as usual! makes me happy), I am not opposed to adding a whole configuration editing feature (env variables, volumes, networks, etc.). It's just that I'm uncertain as to how it should be added, and how it would fit within the "keyboard-first paradigm" if that makes sense. If you have ideas / suggestions, I'm genuinely looking forward to them (previously, someone requested the `overview` feature, and sent me a screenshot of how it could look, and now we have it!). So, yup, I'd be glad to work on that feature provided that I find a way to integrate it without breaking the current state of things.

I hope I could help (especially with the `.env` thing), and don't hesitate at all if I can help further.

**Comment by will-moss** [comment]
It's me again.

I have just tried reproducing your setup : 
- I have Isaiah running locally, with `CUSTOM_DOCKER_HOST = <MACHINE-B-SOCKET>`
- I have Docker installed on Machine B, and my Docker socket exposed via ngrok + socat (because A and B can't communicate directly in my setup)
- I was successfully able to open container shells on B from A

If that provides any help...!

**Comment by Vinylwalk3r** [comment]
I godda say, your "customer supp

ort" is the envy of many :D
Okay, down to buisness.

- Before anything, I'm going to explain my setup in detail so we're on the same page. I've now that me not explaining it in full before caused unneeded confusion / extra work. Here it is:

1. Machine A = Unraid OS (6.12.10) , has got Isaiah running as Docker (and, for testing purposes, a standalone app. NOT AT THE SAME TIME). 
2. Machine B = Ubuntu Server (latest LTS version, I think), has got Docker Engine installed and Docker socket exposed on 2375.
3. They talk to each other over Tailscale since I'm planning on moving Machine B and use it as offsite backup.

About that .env file now:
- Yes, passing a .env file to a standalone Isaiah instance proved to be a real challenge. I took a picture of my terminal and, since I'm not well versed in .env file usage (as previously stated) maybe you or someone knowledgeable could find the flaw thats bugging me.
![Screenshot 2024-07-20 145449](https://github.com/user-attachments/assets/7bbd185a-c56e-49e1-a285-6eacbd143f34)
No matter what I do, I cant get Isaiah to accept the .env file. It is as if it isn't there. Is there some special formatting in the file that I have to do? Some metadata, frontmatter that needs to be added in order for Isaiah to see it? All I've done 
in the .env is to copy / paste the environment variables from my Isaiah docker container deployment. Should that be it?
For example: 
```
MULTI_HOST_ENABLED=true
path/to/multi/host/file:/multi-hosts:ro
etc
```

(about the footnote)
- Wow that was fast! Well done! I think that adding that note will help many future users quickly understanding what happening. I think a standalone app deployment is preferable, since it will allow all of Isaiahs features to work.
I can understand why Sys Shell cant be called up from inside a Docker environment. Since a big part of Dockers foundation is separating the system it runs on from the containers that's running, allowing access to Sys shell would be a massive vulnerability / security breach.

(the EDIT)
- Yeah, I think I will, once I get the .env mess sorted out, deploy Isaiah as a standalone on both my machines. Just gonna have to figure out some Tailscale port forwarding to have it not block Isaiah.

(About the Container Shells crashing)
- No no, I've been bad at explaining here. Sorry. It's not the Container Shells that's crashing, they work fine. No, it was Isaiahs OWN container shell that autoclosed whenever I tried to open it. From inside Unraids UI, I went to access Isaiahs "console", or container shell and it just closed without saying anything. But, as you explained previously, since the Docker container is based on "scratch", it doesn't have a shell of it's own. So having the containers shell crashing is expected behaviour since there is no shell to open in the first place.

(about adding a config editing feature)
- Since I'm a bit pressed for time atm, I'll get back to you on that (either later today or Monday). I have some ideas and I'm gonna make some mockups for you. Can I submit them as a answer here of where would you want them?

Thanks for taking the time to making this awesome app and being so helpful here! I'll get back to you when I can.

**Comment by will-moss** [comment]
Alright!! I think we're seeing the light at the end of the tunnel.

Thanks a lot for the kind words, and for taking the time to explain everything in details.

Regarding the `.env` case :

- You're really just a few seconds away from being done! Judging by your copy-paste, your `.env` file is not well-formatted. Fixing your file should solve all your issues, and have Isaiah load the `.env` file as expected. Let me explain : A `.env` file (commonly called "dotenv" because it's literally named "dotenv / .env") contains environment variables. The goal of such a file is to pass many environment variables to programs on Linux, because doing it on the command-line isn't very elegant / practical when you have more than two variables. Before `.env` files, one would run a command like so : `SETTING_1=VALUE_1 SETTING_2=VALUE_2 isaiah". But now, with a `.env` file, one can just fill a file with one key-value association per line, run `isaiah`, and call it a day (because Isaiah will load the `.env` file automatically, and nowadays, most modern programs do). 

- The `.env` file must follow a simple format :
 - Each line must contain one and only key-value association. 
 - Every value should be enclosed between two quotes (it is not mandatory, but usually preferred)
 - A line can be empty (useful if you want to group key-value associations by "invisible sections" defined by line breaks.)
 - No comments are allowed (no hashtag, no double slash, no slash-asterisk, or any other common comment symbol)
 - Example : MY_SETTING="MY_VALUE"

- If your `.env` file is not correctly formatted, it will be ignored by Isaiah (this is what, I believe, is currently happening). As a result, please find here a link to a sample `.env` file I made for you : https://pastebin.com/HdeKAxM2 (Authentication enabled, Authentication Password defined, Custom port 3001 used, Theme set on "moon", Overview disabled on startup, and you can tweak that as much as you need).

- Reading your `.env` file content, I believe that a few lines (coming from your Docker setup) should be removed to fix the file format. For example, I see "path/to/multi/host/file:/multi-hosts:ro" which is a Docker volume binding. First of all, you don't need any Docker binding now that you're using the standalone app deployment. And finally, the line "path/to/multi/host/file:/multi-hosts:ro" is, indeed, not a proper `.env` line. 

- Regarding the rest : Thanks a lot for clarifying and for describing your setup. It all makes sense now, and I'm happy we were able to shed light on every dark spot 👍 👍 👍 

Regarding the config editing feature, thanks already for suggesting it, and for thinking about it. No hurry at all. Take your time, and (if that's okay for you) you can open an issue dedicated to it when you feel ready (just so that we keep the current issue #5 dedicated to "one" thing, and when we succeed at solving the `.env` case, we can close it).

Thanks again, and crossing my fingers that we've found the culprit this time!

**Comment by Vinylwalk3r** [comment]
Okay, I think I have a rough idea here. First of *disclaimer time* I'm not UI designer at all. So I just throwing a rough and unpolished idea here. But lets hope it 

can inspire something great!

- So, for my first idea, in the "x" menu, when having a container selected, this could be an option:
![X Menu](https://github.com/user-attachments/assets/637749a0-1857-4fc7-b22f-ece9909278d3)
If chosen, a big text box could appear which allows all settings (from either it's compose code or run command) could be edited. See below for a rough example of such a text box

- If you select a image and go to "x" -> "Run Image", instead of it just asking for a container name and then running, it could ask for a name, then ask if you want to input a compose code or run command:
![Input your Docker Compose or Run](https://github.com/user-attachments/assets/c2d12f52-ea76-441c-a11c-10cf253119f2)

I've been thinking, do you think Isaiah could handle compose codes? It would need to 
1. "mkdir new-compose-project" then 
2. "touch (or whatever command is necessary" docker-compose.yml "all the inputted compose code" 
3. then "docker compose up"
Would that be possible, in whatever implementation you choose?

- After the compose / run selection screen, a text box could appear that allows you to input your code / command:
![Input your Docker Compose or Run](https://github.com/user-attachments/assets/5f448407-6999-498b-b6a1-1c50a57bfb2f)
After this, it runs as usual.

Do you think any of this could be doable / fitting for Isaiah?

**Comment by Vinylwalk3r** [comment]
Thanks for your help! Your a real master at explaining, 11/10 through and through!

I read through your answer and you were totally right! I had no clue how to write a proper .env file 😅 The "/path/to/multi/host/file" line had to go completely. If the .env file isn't formatted correctly, Isaiah will treat it as if it doesn't exist.
So I edited my .env files properly, and they worked!! WOOHOO!!!
Now Isaiah works on both systems! 


As a little sidenote....
I also went ahead and created a Systemd service for Isaiah on my Ubuntu server with the config:
```
[Unit]
Description=Isaiah, the docker manager

[Service]
ExecStart=/usr/local/bin/isaiah
Restart=on-failure
Environment="AUTHENTICATION_SECRET=your-secret"
# Setting the node to agent and prepping for auth with Master node
Environment="SERVER_ROLE=Agent"
Environment="MASTER_HOST=IP adress to Master:3000"
Environment="MASTER_SECRET=masters-secret"
Environment="AGENT_NAME=your-agents-name"

[Install]
WantedBy=multi-user.target
```
Now, they're there for anyone to easily run Isaiah as a background service, always on.


I know I'm clogging up this issue report with other stuff right now, but I at least want it out there so others don't have to spend a entire evening learning systemd and override.conf files to just run Isaiah as a background service (daemon)

I think we can finally close this case. Hoowee it's been a lot...Well done and thank you @will-moss for helping me so much!!
