### ISSUE TITLE
Issues connecting to docker.

### ISSUE THREAD

**Issue by ForceConstant** [will-moss/isaiah#7]
I install this on my unraid/linux machine, to evaluate it replacing portainer. I already have portainer installed, so have the same "/var/run/docker.sock:/var/run/docker.sock" volume, but when Isaiah starts it says 0 container, 0 networks... when there are lots of them. Anyway to enable debug or such to see why it isn't connecting to docker?

**Comment by will-moss** [comment]
Thanks for opening the issue.

Could you please share the content of your `docker-compose.yml` file, or your `docker run` command?

Normally, you should see an error at startup if Isaiah wasn't able to connect to Docker. I mean, the server wouldn't start at all, and you wouldn't have access to the UI. Startup checks are performed to make sure that your configuration is alright before spinning up the server. As a result, if you have access to the UI, it should mean that, on the "accessing Docker" part, everything is fine.

One way to "debug", although not so convenient, is to open your browser developer tools, go to the "Network" tab, then filter to see "WS" connections, open the WS connection established between your browser and Isaiah, and read the messages sent and received. That could give a clue on what's going on.

Here's a few questions to try to assess what's going on : 
- Do you have a lot of Docker resources on your system? (100+) (Trying to see if, maybe, the websocket communication is broken due to message size. Then, the fix would be to increase the setting `SERVER_MAX_READ_SIZE`)
- Do you see any error in the Javascript console of your browser? (Open the developer tools (F12 or Ctrl + Shift + i or Cmd + Shift + i), and open the "Console" tab). If so, please copy-paste it here.
- Have you installed Isaiah using a `docker-compose.yml` file? Or using the "Unraid Community Apps"? Please note that I have discovered Unraid just recently, and another user reported using the "Unraid App for Isaiah", but I am not the one who has published or created it. The only "safe place" to go is on Github, on the current repository. I'm not well-versed on the Unraid ecosystem and how "packaging an app" works or even how it has been done on my behalf.

I hope it helps!

**Comment by CptanPanic** [comment]
No errors in browser console.

From Portainer:
![image](https://github.com/user-attachments/assets/28eec25e-ddfa-48f3-9391-4738892539bc)


> version: '3'
> services:
>   isaiah:
>     image: mosswill/isaiah:latest
>     restart: unless-stopped
>     ports:
>       - "90:80"
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>     environment:
>       SERVER_PORT: 80
>       AUTHENTICATION_ENABLED: FALSE


isaiah-isaiah-1  | 2024/08/22 19:00:27 No .env file provided, will continue with system env
isaiah-isaiah-1  | 2024/08/22 19:00:27 Performing verifications before starting
isaiah-isaiah-1  | 2024/08/22 19:00:27 Server starting on port 80

**Comment by will-moss** [comment]
Alright.

Thanks a lot for the screenshot, and for the other elements.

Can I suggest to set the environment variable `SERVER_MAX_READ_SIZE` to a very high number? For example, 900000.

This is just to try to make sure that the issue is, indeed, the number of resources.

At first launch, all the resources are fetched and sent over Websockets, all at once. However, because of the Websockets server implementation, when a message is too big ( size > `SERVER_MAX_READ_SIZE`, it just doesn't flow (and potentially, crashes the server)).

If anyone can try to increase the value of this setting, and confirms that it solves the issue, I will gladly implement a chunk retrieval of the resources, rather than the current all-at-once system.

Thanks again for helping.

**Comment by CptanPanic** [comment]
I changed it to 900000 and same thing.

**Comment by will-moss** [comment]
Thanks a lot for trying.

If it's not too much of a stretch, is there any chance you could try to use Isaiah on an instance with less Docker resources?

Besides, if you see no error in the Javascript console, no crash on the server side, and nothing weird in the Websocket messages, I genuinely have no idea what could be happening. I wonder if, maybe, you're using something like [docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy)? 

Are you able to confirm that the following commands works?

`curl --unix-socket /var/run/docker.sock -X GET http://localhost/containers/json`

It should return the list of all your containers. If it works, it should, at least, enable us to search the mishappening somewhere else.

**Comment by CptanPanic** [comment]
So yes that curl command works, and returns a 112KB json.  Does that correlate to SERVER_MAX_READ_SIZE ?

**Comment by will-moss** [comment]
Thank you very much.

To be honest, I am not a 100% sure, and it's the first time this issue arises.

However, I think the safest thing to do is implementing a chunk-based retrieval of resources, rather than the current all-at-once. I will develop it and make it optional in the settings.

If you don't mind sticking around, I will keep this issue opened, and add a new comment when I have released the feature.

**Comment by will-moss** [comment]
Re,

I was developing the feature and had a gist of it, but I still wanted to perform a few checks before going all-in.

As a result, I have tried to (in bulk) download images, create volumes, networks, and containers, to try to reproduce your environment. Here's a screenshot to demonstrate the idea, with the default settings, on a MacBook Pro : https://ibb.co/kxqF3jc (over the Docker Engine API, the containers alone in my setup represent 218 KB of JSON, which is well handled).

It seems that, on my side at least, the number of resources isn't the issue. Also, I have checked the code responsible for displaying the overview, and I was wrong. This part of the code doesn't send a huge message with all the resources over WebSocket. Rather, it calls the Docker Engine API to list the resources, runs the `len(X)` function to count the elements received, and sends a message over WebSocket with the counts, but that message is tiny.

So, I wanted to ask you : 

- Are you a 100% confident that the Docker socket that Isaiah has access to is the proper one? I am even wondering if having it bounded as a volume for both Portainer and Isaiah could be an issue.

- When you say (or rather, @ForceConstant) "Isaiah starts it says 0 container, 0 networks", are you talking about the overview with the icons, the Docker version, like in my screenshot? Or the overview is fine with the proper counts, but then the Ui is empty?

- Is there any setting in Unraid that could explain what's going on? (I've found this tutorial, for example : https://www.reddit.com/r/unRAID/comments/swz3l3/howto_securing_access_to_your_dockersock_file/)

- Could you copy-paste the output of the command `docker info` here? (Stripping personal info if any)

All in all, I'm afraid that the chunk-retrieval feature won't solve the problem at all, as I believe it lies somewhere else.

**Comment by painteau** [comment]
Hello ! Really interesting issue, as I have the same :)

I installed the docker the same way on 3 servers. It worked perfectly. But then :

![issue](https://github.com/user-attachments/assets/8c1990c4-2b88-4292-8ed8-a5485daef9f5)

Its really interesting that it actually worked, but then....no.

I dont have portainer.

curl --unix-socket /var/run/docker.sock -X GET http://localhost/containers/json
returns a valid json

and docker info returns :
`
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.24+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1+b1
 runc version: 1.1.5+ds1-1+deb12u1
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.0-23-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.903GiB
 Name: *******************************************
 ID: ******************************************
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

**Comment by will-moss** [comment]
Thanks a lot for joining the thread, and for providing these details.

It may have something to do with the Docker Version? (Just thinking out loud, maybe updating Docker is the solution?)

I see on your screenshot `Docker <empty space>` which means that Isaiah wasn't able to retrieve the Docker Version.

Also, from your Docker Info, I see that you are on Docker 20.10.24, while I am on Docker 26.0.0.

Here's my `docker info` output : 

```bash
Client:
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins: 
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1-desktop.1
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1-desktop.1
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.27
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
  scout: Docker Scout (Docker Inc.)
    Version:  v1.6.3
Server:
 Containers: 112
  Running: 111
  Paused: 0
  Stopped: 1
 Images: 86
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.22-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 23.44GiB
 Name: docker-desktop
 ID: a5aacd94-aaa8-49fc-968f-6e006987c94b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/xxxxxxx/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by painteau** [comment]
Hehe. When I posted my comment, I realized ..... Docker version 20 ? Isnt that a little bit old ?

So I clean my apt sources.list and reinstalled docker the official way.

That change my sources.list a little bit, and after a BIG update, my Docker server is now version 27.

And of course : the isaiah container works perfectly !

**Comment by will-moss** [comment]
You're the champ! Thanks a lot for your feedback, and for posting what seems to be the solution.

May I ask @ForceConstant  / @CptanPanic  to try to do the same? I mean, update Docker and see if that works?

Thanks again everyone.

**Comment by painteau** [comment]
No ! Thank you :)

Ah and for info, as I happened to have a unraid/linux server too (with no portainer tho), i tried on it. It worked perfectly.

my docker info on unraid :

Client:
 Version:    24.0.9
 Context:    default
 Debug Mode: false

Server:
 Containers: 33
  Running: 27
  Paused: 0
  Stopped: 6
 Images: 34
 Server Version: 24.0.9
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7c3aca7a610df76212171d*************
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.79-Unraid
 Operating System: Slackware 15.0 x86_64 (post 15.0 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.28GiB
 Name: UNRAID
 ID: 5************----*********---****
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by CptanPanic** [comment]
Interesting, I am on unraid, but have Docker version 20.10.24, build 297e128.  Note unraid 6.12.4, so I will see about updating unraid/docker.

**Comment by CptanPanic** [comment]
Yay I upgraded, so that now I am on 'Docker version 24.0.9, build 2936816' and it works. Thanks everyone.

**Comment by will-moss** [comment]
Thanks a lot for your confirmation.

Wishing you all a great Sunday.
