### ISSUE TITLE
Websocket fails: Message too big

### ISSUE THREAD

**Issue by Nassiel** [will-moss/isaiah#9]
Hi,

After some time, I managed to deploy the Host/Master with the web page and visibility of the other two agents. To one of the agents, all works fine. With the other, I introduce the secret, "Your are now authenticated" (btw there is a typo in your), but then, I see the error again ", You are not authenticated yet", and introduce it again.

The only error I manage to see in the logs (and for some reason sometimes it appears and sometimes it just resets the container is the next:

```txt
2024/08/25 13:38:51 No .env file provided, will continue with system env
2024/08/25 13:38:51 Performing verifications before starting
2024/08/25 13:38:51 Initiating registration with master node
2024/08/25 13:38:51 Performing authentication
2024/08/25 13:38:51 Connection with master node is established
2024/08/25 13:39:21 websocket: close 1009 (message too big)
```

The first is the Host/Master, the second is the one with errors, the third works perfectly fine:
![image](https://github.com/user-attachments/assets/99d00e0e-47c5-4435-ba74-39e9264ff3d3)

It's true that the server is quite busy and has a lot of items on it, containers, volumes, images, etc. I believe it is trying to send all in the same package, and it fails instead of sending it by parts.

**Comment by will-moss** [comment]
Hi,

Thanks a lot for opening the issue and for providing these details.

You are absolutely right, the problem is in the WebSocket communication : The message is too big because everything is sent at once, so the server crashes and restarts, and then it prompts for authentication again (because it has lost its previous state after the crash-restart).

**The quick and dirty solution is to increase the value of the setting `SERVER_MAX_READ_SIZE` on the Master node.**

I will soon publish a release that enables chunked communication, so that resources are sent by chunks, rather than in a big message that can potentially crash the server when there are so many of them (as is your case).

Let me know if the `SERVER_MAX_READ_SIZE` increase fixes the issue, and I will keep this issue open until I publish the chunked communication feature.

**Comment by will-moss** [comment]
Alright, I'm back!

I have published a new release that introduces chunked communication (along with other improvements and fixes) just now.

You should now be able to fix the issue in your multi-node deployment by editing the `.env` settings on the agent that hosts a lot of resources, by adding `SERVER_CHUNKED_COMMUNICATION_ENABLED="TRUE"`. By default, 50 resources are sent by chunk, but you can adjust that to something higher for faster loading speed if you experience UI glitches on first launches and updates.

I hope it works better now! 🙏

**Comment by Nassiel** [comment]
Yeah! Now it works!! :D It's the fastest resolution ever, to be honest. So it's only required in the agent, the host doesn't need it. Right? I will close to keep the issues low, but I'd like to discuss something if you don't mind.

Do you plan to add some... short circuit pattern to the agents if the hosts are down? If I have to make a change, reboot, or just upgrade the version, I need to start the host, and then in 10 VMs, go and restart the agent because it just dies.

**Comment by will-moss** [comment]
Thanks for your feedback! I'm glad it works now. And always happy to discuss.

For your first point, indeed, it should only be required on the agent that has a lot of resources, so that it sends those resources in small chunks rather than all in a single big message. The master node needs no changes.

Regarding your question about the short circuit pattern for the agents, I couldn't agree more, you are completely right. Even when I'm developing and testing the multi-node setup locally, having to restart the agents every time is a real pain. I've just added that feature to my roadmap - implement a reconnect mechanism when connection to the master node is lost.

Regarding the password management, I think there's two distinct points you've mentioned : 
- The navigation not recognizing the field as a password field that can be autofilled : I will fix that in a next release, soon. You're right.
- The password prompt shown on every agent : I have developed the multi-node system with "no password for the agents" in mind. My idea was that, since the agents are never exposed to the public (because they communicate with the master node only, acting like a proxy between the client and the agents), they don't really need a password unless you're in a multi-user philosophy where each user has access to a specific agent only. As a result, I expected people to deploy multi-node setups with authentication disabled on the agents, hence removing the annoying password prompt for those who are in a "1 user, manages X nodes" scenario. Does it make sense? Following that explanation, what do you think would be the best step forward? Disabling authentication on your agents / Implement something to make the UX better / Add documentation about it in the readme?

- Regarding your last point about the multi-host system, is there any chance you could share a little more on your setup? Are you actually combining multi-node and multi-host together? If that can help understand how everything works, here's an explanation on the multi-host : 
  - First and foremost, it is vastly different from the multi-node system. There is no discovery phase, and no real "die" or "disconnection" that could happen.
  -  Normally, in a multi-host deployment, you have, let's say, servers A, B, C, and D. All have Docker installed, and all have their own `/var/run/docker.sock` available locally.
  - From that foundation, Isaiah will try to send requests to these `docker.sock` sockets, which must have been exposed over TCP / SSH / Mounts beforehand.
  - When in a normal (local, no multi-host, no multi-node) deployment Isaiah sends requests to the local `/var/run/docker.sock`, the same thing happens in a multi-host deployment, except that the `/var/run/docker.sock` is elsewhere. Therefore, there is no registration, disconnection, or any other issue (or so I believe) that could arise. The only caveat that comes to my mind is the internet connection, if the socket is exposed over TCP / SSH.

I hope it all makes sense!

Thanks a lot, once again, for the kind words and feedback.

Looking forward to discussing these points 🙏

**Comment by Nassiel** [comment]
> Thanks for your feedback! I'm glad it works now. And always happy to discuss.
I'll reply as carefully as you! :D 


>     * The password prompt shown on every agent : I have developed the multi-node system with "no password for the agents" in mind. My idea was that, since the agents are never exposed to the public (because they communicate with the master node only, acting like a proxy between the client and the agents), they don't really need a password unless you're in a multi-user philosophy where each user has access to a specific agent only. As a result, I expected people to deploy multi-node setups with authentication disabled on the agents, hence removing the annoying password prompt for those who are in a "1 user, manages X nodes" scenario. Does it make sense? Following that explanation, what do you think would be the best step forward? Disabling authentication on your agents / Implement something to make the UX better / Add documentation about it in the readme?

The logic is almost there, IMHO. But you're trying to fulfil two different scenarios.
- Scenario A: I'm a single user with full access to everything, so no need to multiple passwords, AND having passwords make more resilient to an internal attack
- Scenario B: It's a combinatory exposition of one docker node to different users and, most likely, different permissions (can restart but not delete?)

I believe Scenario A is much more common, so I'd focus on that for your specific use case (but you know your audience better). Scenario B is exponentially complex and it is hard to do correctly with the current tools. You must take care of concurrency, request the same action several times, and allow read-one modes, permission management, user management... 

IMHO, If Scenario A is well done, and I NEED a multi-user, I can play with it by deploying the same agent several times to point to different master with different passwords and play with ports. Yes, you'll have a race conditions, but then it's docker who manage them like if 2 devops access the same machine and run the same docker command. Again, if I want to play with roses I may got hurt.... but it's my choice to enter into that garden.

So, personally, I'd focus on do fully A first. To reach it, and I haven't read your code, but I guess the agent initiates a socket, uses the master password to connect and that's all. The master only tries to get the information once you click on it and then asks for the password. If during that "hello" process, you may include "let's try to connect back using my master password" 

1. Then, if it works, all done -> store the token and keep using it. All is transparent and seamless
2. If, on the other hand, you want to keep a different password, eat as a user the complexity -> mark the node as pending and ask the user to introduce the password

It's just a failover, but if, during the deployment, you use the same password for agent and master, it "just works". Second, your browser should only remember the first secret. The subsequent secrets should stay like now because you'll be asked 100 times to "update your password?" which will be annoying or frustrating if you click yes just once. 

This, I think, shouldn't change the logic too much, allows complexity if some users want to, or if you're a paranoic keep using 100 different secrets and paste them manually. If you have several users, deploy some hosts with agents only on suitable machines to have subsets of accesses. In the end, your software is INCREDIBLY light. Having 2 agents or 10 won't make a difference.

Lastly, if you're already a 50 guys devops team, I'd reply, "please, stop deploying and managing manually  individual docker and start using Kubernetes asap"

> Regarding your last point about the multi-host system, is there any chance you could share a little more on your setup? Are you actually combining multi-node and multi-host together? If that can help understand how everything works, here's an explanation on the multi-host :
> 
>     * First and foremost, it is vastly different from the multi-node system. There is no discovery phase, and no real "die" or "disconnection" that could happen.
> 
>     * Normally, in a multi-host deployment, you have, let's say, servers A, B, C, and D. All have Docker installed, and all have their own `/var/run/docker.sock` available locally.
> 
>     * From that foundation, Isaiah will try to send requests to these `docker.sock` sockets, which must have been exposed over TCP / SSH / Mounts beforehand.
> 
>     * When in a normal (local, no multi-host, no multi-node) deployment Isaiah sends requests to the local `/var/run/docker.sock`, the same thing happens in a multi-host deployment, except that the `/var/run/docker.sock` is elsewhere. Therefore, there is no registration, disconnection, or any other issue (or so I believe) that could arise. The only caveat that comes to my mind is the internet connection, if the socket is exposed over TCP / SSH.

Ooooohhh now I get it, so it's not connecting to other Isaiah. It's linking directly to the `docker.sock` published in the LAN. Well, I genuinely think having agents is far safer.
> 
> I hope it all makes sense!
100%
> Thanks a lot, once again, for the kind words and feedback.
> 
> Looking forward to discussing these points 🙏

Thanks for your dedication, it's an absolute pleasure :1st_place_medal:

**Comment by will-moss** [comment]
Alright alright alright! 

Thank you very much once again. Your explanations were clear and extremely helpful. (laughed at the roses/garden hahaha)

I definitely agree with everything you've detailed, and it helped me see clearer through the different use-cases.

As a result, I've just published a new release that should include every improvement discussed in your comment.

Namely : 

- There is now an auto-reconnect mechanism on Agents : When connection to the Master node is lost, Agents will try to reconnect every 30 seconds (can be customized using the `AGENT_REGISTRATION_RETRY_DELAY` setting). 

- There is now the proper HTML markup and JS behavior to spur browsers to prompt you to save and reuse your password during authentication. Please note that, in my experience at least, it seemed to work well on Edge, Firefox, Safari, Chrome, and Brave. **However**, it seems mandatory to be on HTTPS for it to work consistently.

- There is now an auto-login to the agents, and I tried to make it as seamless as possible : 
  - I tried first to implement your idea, but it came with a few drawbacks : 
    - If the secret is configured as a hash, the Master node can't auto-login to the Agent, because it doesn't know the raw secret. (One could argue, implementing authentication by raw hash could be a solution)
    - The way the project was designed, nothing is really perfectly sequential. As a result, adding code to manage another auth scenario seemed to add too much complexity and make the maintenance harder (because everything is in a single codebase, with parts that are parallelized / async, and parts that depend on the Master/Agent role, it's already a miracle (IMHO) that the code is clean, documented, and well put together).
    - I'm not saying that implementing your idea is impossible, but it seemed to create more issues than it solved.  (By the way, you are 100% correct about how Master-Agent communication is implemented!).
  - For all these reasons, I have implemented it differently : 
    - The auto-login is initiated by the client, using the secret typed in the browser, when switching to a new agent.
    - When auto-login is performed, no pop-up is shown, and no delay between operations is added, even though the authentication process still happens in the background.

I hope everything works well on your end, and makes the UX better than it was before.

Thanks a ton once again!!!
